import os
import pytest
import pandas as pd
from hypothesis import given, settings, HealthCheck
import hypothesis.strategies as st
from unittest.mock import patch, MagicMock

# Dynamically import the generator
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from generator import SimulatorEngine

@pytest.fixture
def mock_engine(tmp_path):
    """
    Creates a SimulatorEngine instance with a mocked DataFrame to bypass raw local Kaggle loading
    during pytest isolation. Output directory set to pytest tmp.
    """
    mock_data = {
        'Date': pd.to_datetime(['1985-01-01', '1985-01-02']),
        'Open': [20.0, 21.0],
        'High': [22.0, 23.0],
        'Low': [19.0, 20.0],
        'Close/Last': [21.5, 22.5],
        'Volume': [100000, 150000]
    }
    mock_df = pd.DataFrame(mock_data)
    
    # We patch __init__ so it doesn't fail trying to read missing files in CI environments
    with patch.object(SimulatorEngine, '__init__', return_value=None):
        engine = SimulatorEngine()
        engine.stock_df = mock_df
        engine.output_base_dir = str(tmp_path)
        
        # Manually create the explicit staging subdirectories
        os.makedirs(os.path.join(tmp_path, "users"), exist_ok=True)
        os.makedirs(os.path.join(tmp_path, "transactions"), exist_ok=True)
        
        yield engine

# Property-Based Testing (PBT) - Security and Data Constraints Base validation
@settings(max_examples=5, deadline=None, suppress_health_check=[HealthCheck.function_scoped_fixture]) # We keep examples low and suppress the healthcheck
@given(st.integers(min_value=120, max_value=2000))
def test_generator_user_properties(mock_engine, total_users):
    """
    Hypothesis Property Check: Given varying bounds of N total_users dynamically generated by Faker, 
    the system must ALWAYS generate exactly N users, the user IDs must be universally unique, and 
    the geo-segmentation MUST guarantee >30% LATAM distributions.
    """
    users_df = mock_engine.generate_users(total_users=total_users)
    
    # Assert Exact Generation Target
    assert len(users_df) == total_users
    
    # Assert Uniqueness
    assert len(users_df['user_id'].unique()) == total_users
    
    # Assert PBT Constraints for Geo-Targeting Layer
    latam_countries = {"MX", "BR", "AR", "CO"}
    actual_latam_count = users_df['country'].isin(latam_countries).sum()
    
    # Ensure it's explicitly generated to our standard 35% hard constraint
    assert actual_latam_count >= int(total_users * 0.30), "LATAM generation violated threshold"
    
def test_process_chunk(mock_engine):
    """
    Explicit integration validation for Pandas vectorization outputs.
    """
    users_df = mock_engine.generate_users(total_users=10) # Minimal users for fast execution
    
    # Process overlapping chunk matching the mock_engine bounds (1985)
    mock_engine.process_chunk(users_df, start_year=1980, end_year=1990, batch_name="test_batch")
    
    # Verify file was flushed to disk
    out_file = os.path.join(mock_engine.output_base_dir, "transactions", "test_batch.parquet")
    assert os.path.exists(out_file)
    
    # Verify Schema and Vectorization fidelity
    df = pd.read_parquet(out_file)
    expected_cols = [
        'transaction_id', 'user_id', 'trade_date', 'trade_type', 'quantity',
        'market_open', 'market_high', 'market_low', 'market_close', 'market_volume'
    ]
    for col in expected_cols:
        assert col in df.columns, f"Missing vectorization assigned column: {col}"
